[package]
name = "coordinator-enclave"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
lnurl = ["coordinator-escrow-verifier/lnurl"]

[dependencies]
coordinator-escrow-verifier = { path = "../coordinator-escrow-verifier" }
keymeld-core = { git = "https://github.com/tee8z/keymeld", tag = "v0.5.0", default-features = false, features = ["escrow", "enclave"] }
keymeld-enclave = { git = "https://github.com/tee8z/keymeld", tag = "v0.5.0", default-features = false, features = ["escrow"] }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
