[workspace]
members = ["cargo:crates/server"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Path that installers should place binaries in
install-path = "$HOME/.coordinator"
# Artifacts to include
artifacts = ["bin"]
# Additional files/directories to include
include = [
    "crates/public_ui/",
    "crates/admin_ui/",
]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Whether to install an updater program
install-updater = true
# GitHub build setup workflow
github-build-setup = "../../git_duckdb/build-setup.yml"

[dist.github-custom-runners]
global = "ubuntu-22.04"
aarch64-apple-darwin = "macos-14"
x86_64-unknown-linux-gnu = "ubuntu-22.04"

[dist.dependencies.apt]
musl-tools = '*'
