[workspace]
members = ["npm:crates/public_ui" ,"cargo:crates/server",]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
install-path = "$HOME/.coordinator"

artifacts = ["bin"]
include = [
    "crates/public_ui/",
    "crates/admin_ui/",
]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
install-updater = true
github-build-setup = "../../git_duckdb/build-setup.yml"

[dist.dependencies.apt]
musl-tools = '*'
