level = "debug"
ui_dir = "./crates/server/ui"
admin_ui_dir = "./crates/server/admin_ui"
host = "127.0.0.1"
port = "9990"
private_url = "http://127.0.0.1:9990"
remote_url = "http://127.0.0.1:9990"
oracle_url = "https://www.4casttruth.win"
#oracle_url = "http://127.0.0.1:9100"
competition_db = "./competition_data"
