[package]
name = "coordinator-verifier-enclave"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
lnurl = ["coordinator-escrow-verifier/lnurl"]
payout-witness-local = ["coordinator-escrow-verifier/payout-witness-local"]

[dependencies]
coordinator-escrow-verifier = { path = "../coordinator-escrow-verifier" }
keymeld-core = { git = "https://github.com/tee8z/keymeld", rev = "f082e28b384a9236c69162838b8a68f832c75f82", default-features = false, features = ["escrow", "enclave"] }
keymeld-enclave = { git = "https://github.com/tee8z/keymeld", rev = "f082e28b384a9236c69162838b8a68f832c75f82", default-features = false, features = ["escrow"] }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
