[package]
name = "coordinator-verifier-enclave"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
lnurl = ["coordinator-escrow-verifier/lnurl"]

[dependencies]
coordinator-escrow-verifier = { path = "../coordinator-escrow-verifier" }
keymeld-core = { git = "https://github.com/tee8z/keymeld", rev = "3508ed9360f6daba48e251bb941ef34d9a538556", default-features = false, features = ["escrow", "enclave"] }
keymeld-enclave = { git = "https://github.com/tee8z/keymeld", rev = "3508ed9360f6daba48e251bb941ef34d9a538556", default-features = false, features = ["escrow"] }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
