//! Bundles the dashboard's styles and scripts into one stylesheet and one script, minified, and
//! names each by its content's hash so browsers can cache them for good.
//!
//! Styles and scripts live beside the Rust that renders them, under `src/server/`. htmx comes
//! first, as published, from the workspace's `vendor/htmx/`: see the README there for where each
//! file comes from and its hash.

use std::{
    env,
    error::Error,
    fs, io,
    path::{Path, PathBuf},
};

use lightningcss::stylesheet::{MinifyOptions, ParserOptions, PrinterOptions, StyleSheet};
use oxc::{
    allocator::Allocator,
    codegen::{Codegen, CodegenOptions},
    minifier::{Minifier, MinifierOptions},
    parser::Parser,
    span::SourceType,
};
use sha2::{Digest, Sha256};

/// The vendored scripts, relative to the workspace root, in the order they must load: the SSE
/// extension registers with htmx.
const VENDOR: [&str; 2] = [
    "vendor/htmx/4.0.0/htmx.min.js",
    "vendor/htmx/4.0.0/ext/hx-sse.min.js",
];

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/server");

    let manifest = env::var_os("CARGO_MANIFEST_DIR").ok_or("CARGO_MANIFEST_DIR is missing")?;
    let output = env::var_os("OUT_DIR").ok_or("OUT_DIR is missing")?;
    let root = Path::new(&manifest);
    let workspace = root.join("../..");
    let output = Path::new(&output);
    let server = root.join("src/server");

    let mut css_files = Vec::new();
    let mut js_files = Vec::new();
    collect_assets(&server, &mut css_files, &mut js_files)?;
    // The base stylesheet first, so components can refine it.
    let base = server.join("assets/synth.css");
    css_files.sort_by(|left, right| (left != &base, left).cmp(&(right != &base, right)));
    js_files.sort();

    let css = concatenate(&css_files, "\n")?;
    let mut stylesheet = StyleSheet::parse(
        &css,
        ParserOptions {
            filename: "src/server (combined CSS)".into(),
            ..ParserOptions::default()
        },
    )
    .map_err(|error| io::Error::other(format!("parse CSS: {error}")))?;
    stylesheet
        .minify(MinifyOptions::default())
        .map_err(|error| io::Error::other(format!("minify CSS: {error}")))?;
    let css = stylesheet
        .to_css(PrinterOptions {
            minify: true,
            ..PrinterOptions::default()
        })?
        .code;

    let mut js = Vec::new();
    for name in VENDOR {
        let path = workspace.join(name);
        println!("cargo::rerun-if-changed={}", path.display());
        js.extend_from_slice(&fs::read(&path).map_err(|error| {
            io::Error::new(error.kind(), format!("read {}: {error}", path.display()))
        })?);
        // Semicolons keep one script's last statement apart from the next.
        js.extend_from_slice(b"\n;\n");
    }
    for path in &js_files {
        let source = fs::read_to_string(path)?;
        js.extend_from_slice(minify_js(path, &source)?.as_bytes());
        js.extend_from_slice(b";\n");
    }

    let css_url = write_asset(output, "css", css.as_bytes())?;
    let js_url = write_asset(output, "js", &js)?;
    fs::write(
        output.join("assets.rs"),
        format!(
            r#"// Generated by build.rs; edit the styles and scripts in src/server/ instead.
pub const CSS_URL: &str = {css_url:?};
pub const JS_URL: &str = {js_url:?};
pub const CSS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/synth.css"));
pub const JS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/synth.js"));
"#
        ),
    )?;
    Ok(())
}

/// Minify one of synth's own scripts. The page loads a classic deferred script, so the source
/// keeps global-script semantics. oxc's API changes between 0.x versions; keep its calls here.
fn minify_js(path: &Path, source: &str) -> Result<String, Box<dyn Error>> {
    let allocator = Allocator::default();
    let parsed = Parser::new(&allocator, source, SourceType::script()).parse();
    if let Some(error) = parsed.diagnostics.errors().next() {
        return Err(format!("{}: {error}", path.display()).into());
    }
    let mut program = parsed.program;
    let minified = Minifier::new(MinifierOptions::default()).minify(&allocator, &mut program);
    Ok(Codegen::new()
        .with_options(CodegenOptions::minify())
        .with_scoping(minified.scoping)
        .build(&program)
        .code)
}

fn collect_assets(
    directory: &Path,
    css: &mut Vec<PathBuf>,
    javascript: &mut Vec<PathBuf>,
) -> io::Result<()> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            collect_assets(&path, css, javascript)?;
            continue;
        }
        match path.extension().and_then(|extension| extension.to_str()) {
            Some("css") => css.push(path),
            Some("js") => javascript.push(path),
            _ => {}
        }
    }
    Ok(())
}

fn concatenate(files: &[PathBuf], separator: &str) -> io::Result<String> {
    let mut combined = String::new();
    for path in files {
        let source = fs::read_to_string(path).map_err(|error| {
            io::Error::new(error.kind(), format!("read {}: {error}", path.display()))
        })?;
        combined.push_str(&source);
        combined.push_str(separator);
    }
    Ok(combined)
}

fn write_asset(output: &Path, extension: &str, bytes: &[u8]) -> io::Result<String> {
    // Only Cargo's output directory holds generated files; the binary embeds them.
    fs::write(output.join(format!("synth.{extension}")), bytes)?;
    let digest = Sha256::digest(bytes);
    Ok(format!("/assets/synth.{digest:x}.{extension}"))
}
