//! Bundles the dashboard's styles and scripts into one stylesheet and one script, minified, and
//! names each by its content's hash so browsers can cache them for good.
//!
//! Styles and scripts live beside the Rust that renders them, under `src/server/`.

use std::{
    env,
    error::Error,
    fs, io,
    path::{Path, PathBuf},
};

use better_minify_js::{minify, Session, TopLevelMode};
use lightningcss::stylesheet::{MinifyOptions, ParserOptions, PrinterOptions, StyleSheet};
use sha2::{Digest, Sha256};

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/server");

    let manifest = env::var_os("CARGO_MANIFEST_DIR").ok_or("CARGO_MANIFEST_DIR is missing")?;
    let output = env::var_os("OUT_DIR").ok_or("OUT_DIR is missing")?;
    let root = Path::new(&manifest);
    let output = Path::new(&output);
    let server = root.join("src/server");

    let mut css_files = Vec::new();
    let mut js_files = Vec::new();
    collect_assets(&server, &mut css_files, &mut js_files)?;
    // The base stylesheet first, so components can refine it.
    let base = server.join("assets/synth.css");
    css_files.sort_by(|left, right| (left != &base, left).cmp(&(right != &base, right)));
    js_files.sort();

    let css = concatenate(&css_files, "\n")?;
    let mut stylesheet = StyleSheet::parse(
        &css,
        ParserOptions {
            filename: "src/server (combined CSS)".into(),
            ..ParserOptions::default()
        },
    )
    .map_err(|error| io::Error::other(format!("parse CSS: {error}")))?;
    stylesheet
        .minify(MinifyOptions::default())
        .map_err(|error| io::Error::other(format!("minify CSS: {error}")))?;
    let css = stylesheet
        .to_css(PrinterOptions {
            minify: true,
            ..PrinterOptions::default()
        })?
        .code;

    // Newlines end trailing line comments; semicolons separate standalone scripts.
    let own = concatenate(&js_files, "\n;\n")?;
    let session = Session::new();
    let mut js = Vec::new();
    // The page loads a classic deferred script, so keep global-script semantics.
    minify(&session, TopLevelMode::Global, own.as_bytes(), &mut js)
        .map_err(|error| io::Error::other(format!("minify src/server JavaScript: {error:?}")))?;

    let css_url = write_asset(output, "css", css.as_bytes())?;
    let js_url = write_asset(output, "js", &js)?;
    fs::write(
        output.join("assets.rs"),
        format!(
            r#"// Generated by build.rs; edit the styles and scripts in src/server/ instead.
pub const CSS_URL: &str = {css_url:?};
pub const JS_URL: &str = {js_url:?};
pub const CSS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/synth.css"));
pub const JS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/synth.js"));
"#
        ),
    )?;
    Ok(())
}

fn collect_assets(
    directory: &Path,
    css: &mut Vec<PathBuf>,
    javascript: &mut Vec<PathBuf>,
) -> io::Result<()> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            collect_assets(&path, css, javascript)?;
            continue;
        }
        match path.extension().and_then(|extension| extension.to_str()) {
            Some("css") => css.push(path),
            Some("js") => javascript.push(path),
            _ => {}
        }
    }
    Ok(())
}

fn concatenate(files: &[PathBuf], separator: &str) -> io::Result<String> {
    let mut combined = String::new();
    for path in files {
        let source = fs::read_to_string(path).map_err(|error| {
            io::Error::new(error.kind(), format!("read {}: {error}", path.display()))
        })?;
        combined.push_str(&source);
        combined.push_str(separator);
    }
    Ok(combined)
}

fn write_asset(output: &Path, extension: &str, bytes: &[u8]) -> io::Result<String> {
    // Only Cargo's output directory holds generated files; the binary embeds them.
    fs::write(output.join(format!("synth.{extension}")), bytes)?;
    let digest = Sha256::digest(bytes);
    Ok(format!("/assets/synth.{digest:x}.{extension}"))
}
