//! Bundles the browser assets that live beside the templates.
//!
//! Every `.js` and `.css` file under `src/templates` belongs to the component
//! beside it. This script minifies them (oxc for scripts, lightningcss for
//! styles), concatenates them into `OUT_DIR` and
//! writes `assets.rs`, which embeds each file (plain and gzipped) with
//! `include_bytes!` under a URL containing a hash of its content. Nothing is
//! written to the source tree; only the separately built WASM package is still
//! served from disk.

use std::{
    env,
    error::Error,
    fmt::Write as _,
    fs,
    io::{self, Write as _},
    path::{Path, PathBuf},
};

use flate2::{write::GzEncoder, Compression};
use lightningcss::stylesheet::{MinifyOptions, ParserOptions, PrinterOptions, StyleSheet};
use oxc::{
    allocator::Allocator,
    codegen::{Codegen, CodegenOptions},
    minifier::{Minifier, MinifierOptions},
    parser::Parser,
    span::SourceType,
};
use sha2::{Digest, Sha256};

/// Directories whose scripts make up the public site's bundle, in load order.
const PUBLIC_DIRS: &[&str] = &["shared", "components", "fragments", "pages", "layouts"];
/// The public bundle's entry point; it runs after every other script.
const PUBLIC_ENTRY: &str = "base.js";
/// Directories whose scripts make up the operator dashboard's bundle.
const ADMIN_DIRS: &[&str] = &["admin"];

struct Asset {
    /// Rust constant naming the asset in `assets.rs`.
    constant: &'static str,
    /// File stem of the public URL, before the hash.
    stem: &'static str,
    extension: &'static str,
    content_type: &'static str,
    bytes: Vec<u8>,
}

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=build.rs");
    let manifest = env::var_os("CARGO_MANIFEST_DIR").ok_or("CARGO_MANIFEST_DIR is missing")?;
    let output = env::var_os("OUT_DIR").ok_or("OUT_DIR is missing")?;
    let templates = Path::new(&manifest).join("src/templates");
    let output = Path::new(&output);

    let mut files = Vec::new();
    collect(&templates, &mut files)?;
    files.sort();
    // Directories too, so added or removed files trigger a rebuild.
    println!("cargo::rerun-if-changed={}", templates.display());
    for file in &files {
        println!("cargo::rerun-if-changed={}", file.display());
    }

    let static_dir = templates.join("static");
    let assets = [
        Asset {
            constant: "APP_JS",
            stem: "app",
            extension: "js",
            content_type: "text/javascript; charset=utf-8",
            bytes: minify_script(&public_scripts(&templates, &files)?, "app")?,
        },
        Asset {
            constant: "ADMIN_JS",
            stem: "admin",
            extension: "js",
            content_type: "text/javascript; charset=utf-8",
            bytes: minify_script(&scripts_in(&templates, ADMIN_DIRS, &files), "admin")?,
        },
        Asset {
            constant: "STYLES_CSS",
            stem: "styles",
            extension: "css",
            content_type: "text/css; charset=utf-8",
            bytes: stylesheet(&static_dir.join("styles.css"), &files)?,
        },
        // Vendored as published: htmx.org 1.9.10, dist/htmx.min.js.
        Asset {
            constant: "HTMX_JS",
            stem: "htmx",
            extension: "js",
            content_type: "text/javascript; charset=utf-8",
            bytes: fs::read(static_dir.join("htmx-1.9.10.min.js"))?,
        },
        Asset {
            constant: "USA_MAP_SVG",
            stem: "usa-map",
            extension: "svg",
            content_type: "image/svg+xml",
            bytes: fs::read(static_dir.join("usa-map.svg"))?,
        },
    ];

    let mut generated =
        String::from("// Generated by build.rs; edit the files under src/templates instead.\n");
    for asset in &assets {
        let file = format!("{}.{}", asset.stem, asset.extension);
        fs::write(output.join(&file), &asset.bytes)?;
        fs::write(output.join(format!("{file}.gz")), gzip(&asset.bytes)?)?;
        let digest = hex::encode(Sha256::digest(&asset.bytes));
        let url = format!("/assets/{}.{}.{}", asset.stem, &digest[..16], asset.extension);
        writeln!(
            generated,
            "pub const {constant}: Asset = Asset {{ url: {url:?}, content_type: {content_type:?}, \
             bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file}\")), \
             gzip: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file}.gz\")) }};",
            constant = asset.constant,
            content_type = asset.content_type,
        )?;
    }
    let constants: Vec<_> = assets.iter().map(|asset| asset.constant).collect();
    writeln!(generated, "pub const ALL: &[Asset] = &[{}];", constants.join(", "))?;
    fs::write(output.join("assets.rs"), generated)?;
    Ok(())
}

fn collect(directory: &Path, files: &mut Vec<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            collect(&path, files)?;
        } else {
            files.push(path);
        }
    }
    Ok(())
}

fn has_extension(path: &Path, extension: &str) -> bool {
    path.extension().is_some_and(|found| found == extension)
}

/// Scripts under `dirs`, one directory after another, each sorted by path.
fn scripts_in(templates: &Path, dirs: &[&str], files: &[PathBuf]) -> Vec<PathBuf> {
    dirs.iter()
        .flat_map(|dir| {
            let root = templates.join(dir);
            files
                .iter()
                .filter(move |file| file.starts_with(&root) && has_extension(file, "js"))
                .cloned()
        })
        .collect()
}

fn public_scripts(templates: &Path, files: &[PathBuf]) -> Result<Vec<PathBuf>, String> {
    let mut scripts = scripts_in(templates, PUBLIC_DIRS, files);
    let entry = scripts
        .iter()
        .position(|file| file.file_name().is_some_and(|name| name == PUBLIC_ENTRY))
        .ok_or_else(|| format!("the public bundle needs its entry point {PUBLIC_ENTRY}"))?;
    let entry = scripts.remove(entry);
    scripts.push(entry);
    Ok(scripts)
}

/// Minify each script on its own and join them. Each is parsed as a classic
/// script, so its top-level names stay global and are not renamed. A file the
/// parser rejects fails the build.
fn minify_script(files: &[PathBuf], name: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut bundle = String::new();
    for file in files {
        let source = fs::read_to_string(file)?;
        let allocator = Allocator::default();
        let parsed = Parser::new(&allocator, &source, SourceType::script()).parse();
        if let Some(error) = parsed.errors.first() {
            return Err(format!("{name}.js: {}: {error}", file.display()).into());
        }
        let mut program = parsed.program;
        let minified = Minifier::new(MinifierOptions::default()).minify(&allocator, &mut program);
        let code = Codegen::new()
            .with_options(CodegenOptions::minify())
            .with_scoping(minified.scoping)
            .build(&program)
            .code;
        bundle.push_str(&code);
        // Semicolons keep one script's last statement apart from the next.
        bundle.push_str(";\n");
    }
    Ok(bundle.into_bytes())
}

/// Global styles first, then every component's styles, minified as one sheet.
fn stylesheet(base: &Path, files: &[PathBuf]) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut css = fs::read_to_string(base)?;
    for file in files {
        if has_extension(file, "css") && file != base {
            css.push('\n');
            css.push_str(&fs::read_to_string(file)?);
        }
    }
    let mut sheet = StyleSheet::parse(
        &css,
        ParserOptions {
            filename: "src/templates (combined CSS)".into(),
            ..ParserOptions::default()
        },
    )
    .map_err(|error| io::Error::other(format!("parse CSS: {error}")))?;
    sheet
        .minify(MinifyOptions::default())
        .map_err(|error| io::Error::other(format!("minify CSS: {error}")))?;
    let printed = sheet
        .to_css(PrinterOptions {
            minify: true,
            ..PrinterOptions::default()
        })
        .map_err(|error| io::Error::other(format!("print CSS: {error}")))?;
    Ok(printed.code.into_bytes())
}

fn gzip(bytes: &[u8]) -> io::Result<Vec<u8>> {
    let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
    encoder.write_all(bytes)?;
    encoder.finish()
}
