[package]
name = "coordinator-lnurl-relay"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
coordinator-escrow = { path = "../coordinator-escrow", features = ["networking"] }
keymeld-core = { git = "https://github.com/tee8z/keymeld", rev = "98f3420dee497508d2c1ff19180ea795dab5a40e", default-features = false, features = ["networking"] }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-vsock = "0.7.2"
tracing = "0.1"
