[package]
name = "coordinator-lnurl-relay"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
coordinator-escrow = { path = "../coordinator-escrow", features = ["networking"] }
keymeld-core = { git = "https://github.com/tee8z/keymeld", rev = "70c9b3b79e4701c2d75c9d7a85a5614b3d369692", default-features = false, features = ["networking"] }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-vsock = "0.7.2"
tracing = "0.1"
